---
title: "About"
subtitle: "A little bit more about me"
---

## Who I am
I am originally from São Luís, Maranhão state, Brazil, an environmentally and culturally vibrant place with an incredible fauna and flora. Maranhão was where I fell in love with nature and where I started my academic trajectory. Besides being a researcher, I am an avid traveler having been to 15 countries across South and North America, Asia, and Europe. I really enjoy learning and immersing myself in other cultures, ways of living, and phylosophies about how to interact with nature and live life. I believe that we must keep being fascinated by the world and what it offers!

## Professional background
In my undergraduate days at the Federal University of Maranhão, I worked as a research intern in multiple laboratories. I first started as an undergrad intern in a project studying the ecology of frugivore butterflies in an Amazon forest patch. While I had a great time there, I knew that my passion had always been sharks and rays. I then started a project using DNA barcoding to identify shark and ray species landed by fishers in the state. Despite Maranhão's fishing fleet comprising mostly small-scale commercial fisheries, Maranhão is one of the largest fish producers in Brazil, with abundant (though declining) stocks of large bony and cartilaginous fishes and thousands of fishing boats. This prompted me to begin this DNA barcoding project, which turned out to be my senior thesis and led to one of my most important [first-author publications](https://www.nature.com/articles/s41598-018-21683-5) to this day.

After graduating with a BS in Biological Sciences, I immediately started a Master's degree in Animal Biology at the Federal University of Pernambuco. I continued studying the sharks of Maranhão state, but now in a completely different manner. I carried out the first-ever study in South America employing vertebrae microchemistry to study habitat use patterns of a shark species. This super interesting methodology uses the trace element (Sr, Ba, Mn, etc.) concentrations along the shark's vertebra to understand in what types of habitat each shark has lived during its entire life! With this, we can figure out in what kind of environment they live at each life stage, compare them between sexes, and suggest main areas where we could place spatial fishing restrictions (i.e., Marine Protected Areas). Since I started working on this, we have published papers in [Frontiers in Marine Science](https://www.frontiersin.org/journals/marine-science/articles/10.3389/fmars.2020.00125/full), [Marine Biology](https://link.springer.com/article/10.1007/s00227-025-04599-3), [Journal of Fish Biology](https://onlinelibrary.wiley.com/doi/abs/10.1111/jfb.14858), and [Estuarine, Coastal and Shelf Science](https://www.sciencedirect.com/science/article/abs/pii/S0272771424003494) journals. In all of these studies, we demonstrated that several species of sharks and rays use the Brazilian Amazon Coast (which comprises Maranhão) is an Essential Fish Habitat because they fulfill their entire life cycle in the same area. Our findings have supported the classification a portion of Maranhão's coast as an [Important Shark and Ray Area (ISRA)](https://sharkrayareas.org/portfolio-item/reentrancias-maranhenses-isra/). During this time, I also authored papers using models of [species distribution](https://onlinelibrary.wiley.com/doi/abs/10.1002/aqc.3293) and [population dynamics](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0236146) to uncover the geographic range and extinction risk of the smalltail shark (*Carcharhinus porosus*).

## PhD research
Although excited about all this research, I understood that I still had a lot to learn on how to make more effective and cutting-edge science bridging concepts from other fields to make stronger research and policy-oriented suggestions. I then decided take my career abroad and started a PhD in Environmental Science and Management at the world renowned Bren School in the beautiful UC Santa Barbara. During my time at UCSB, I developed strong data science skills (machine learning, simulations, spatial analyses, and ecological modeling) focused on research reproducibility and open science principles. For my dissertation, I developed a research agenda on the bioeconomic synergies that enable fisheries to increase the extinction risk of aquatic species. My PhD project focused on fisheries bycatch issues and the luxury seafood market for shark fins and fish maw (the dried gas bladder of bony fishes), which are high-value delicacies in Southeast Asia. Two of my chapters have been published in Fish and Fisheries already. In the [first](https://onlinelibrary.wiley.com/doi/full/10.1111/faf.12858) we laid the theoretical basis for how open-access fisheries catching multiple species can cause the least productive species to go extinct while maintaining profitability. In the [second](https://onlinelibrary.wiley.com/doi/full/10.1111/faf.12892) we use machine learning to estimate the at-vessel and post-release mortality rates for over 350 species of sharks caught by longlines, and then use these estimates to simulate the effects of retention bans on their populations. In the third chapter, which is almost finished, I use a set of Ordered Forest Models, a newly developed machine learning algorithm for ordered data, to understand the drivers of global serial exploitation (sequential addition of countries and species) for the shark fin and fish maw markets. By doing this, I'll predict which currently unexploited species can enter these markets in the near future and where will fisheries for them be developed. I believe this paper will be a game changer in our ability to fight illegal, unreported and unregulated (IUU) fisheries and for the listing of species in CITES.
