---
title: "Publications"
number-sections: false
number-offset: 0
---

**Peer-reviewed publications**

**In-review**

Alvarenga, M.; Bunholi, I.; Adachi, A. C. L. ; Merten Cruz, M.; **Manir Feitosa, L.**; V. de Jesus, E.; Leda Lopes, M.; Povil, C.; Souza, D.; Torres, Y.; Solé-Cava, A.; Rodrigues Domingues, R.; Charvet, P.; Paes da Cruz, V. Rapid DNA/eDNA-based ID tools for improved Chondrichthyes monitoring and management. *Molecular Ecology Resources*.

Burns, E.; Wang, K.; Bradley, D.; D'Costa, N.; **Feitosa, L.**; Schiller, L.; Worm, B.; Gephart, J.; McDonald, G. The impact of shark finning regulations on the trade of shark products. *Nature Communications*.

**Published**

Gupta, T., Bashyal, R., Anagnostou, M.; Dhanda, S.; Djagoun, J.; **Manir Feitosa, L.**; Hatten, C.; Hunter, S.; Mutezo, T.; Nurbandi, W.; Pizarro, A.; Sackey, H.; Milner-Gulland, E.J.; Oldfield, T.; Challender, D. (2025). Resolving uncertainties in the legality of wildlife trade to support better outcomes for wildlife and people. Conservation Letters, 18, e13110. [link](https://doi.org/10.1111/conl.13110)

**Feitosa, L. M.**, Caughman, A. M., D’Costa, N. G., Orofino, S., Burns, E. S., Schiller, L., Worm, B., Bradley, D. (2025). Retention bans are beneficial but insufficient to stop shark overfishing. Fish and Fisheries, 26(3), 473-487. [link](https://doi.org/10.1111/faf.12892)

**Feitosa, L. M.** & Lessa, R. P. T. (2025). Brazilian Amazon Coast is an essential habitat for threatened and evolutionarily distinct sharks and rays. Marine Biology, 172(2), 1-13. [link](https://doi.org/10.1007/s00227-025-04599-3) 

**Feitosa, L. M.**, Burgess, M. G., Free, C., Gaines, S. D. (2024). Synergies between price and life history enhance extinction risk in open-access fisheries. Fish and Fisheries, 25(6), 972-984. [link](https://doi.org/10.1111/faf.12858)

Queiroz, A. P. B., **Feitosa, L. M.**, Santana, F. M., Lessa, R. P. T. (2024) Stable isotopes and vertebrae microchemistry reveal crucial habitats for three heavily fished coastal stingrays in the Western Atlantic Ocean. Estuarine, Coastal and Shelf Science, 309, 108961. [link](https://doi.org/10.1016/j.ecss.2024.108961)

Worm, B., Orofino, S., Burns, E., D’Costa, N., **Feitosa, L. M.**, Palomares, D., Schiller, L., Bradley, D. (2024). Global shark fishing mortality still rising despite widespread regulatory change. Science, 383, 225-230. [link](https://doi.org/10.1126/science.adf8984)

da Costa, J. A., Martins, A. P. B., **Feitosa, L. M.**, Júnior, V. H., Carvalho, I. E. M., & Nunes, J. L. S. (2021). Acidentes causados pela arraia fluvial Potamotrygon motoro em comunidades lacustres em Território do bioma Oriental da Amazônia. Saúde e meio ambiente: revista interdisciplinar, 10, 254-265. [link](https://doi.org/10.24302/sma.v10.3733)

**Feitosa, L. M.**, Queiroz, A. P. N., Labonne, M., Dressler, V. L., Lessa, R. P. (2021). Habitat use and nursery evaluation of the longnose stingray *Hypanus guttatus* (Bloch & Schneider, 1801) using vertebral microchemistry. Journal of Fish Biology, 99(5), 1538-1549. [link](https://doi.org/10.1111/jfb.14858)

Raoult, V., Grant, M. I., Barbosa Martins, A. P., **Feitosa, L. M.**, Braccini, M., Cardeñosa, D., Carlson, J., Chin, A., Curtis, T., Carvalho-Costa, L. F., Rodrigues-Filho, L. F., Giarrizzo, T., Nunes, J. L. S., Sales, J. B. L., Williamson, J. E., Simpfendorfer, C. A. (2021). Assigning shark fin origin using species distribution models needs a reality check. Biology Letters, 17(7), 20200907. [link](https://doi.org/10.1098/rsbl.2020.0907)

Santana, F. M., **Feitosa, L. M.**, Lessa, R. P. (2020). From plentiful to critically endangered: Demographic evidence of the artisanal fisheries impact on the smalltail shark (*Carcharhinus porosus*) from Northern Brazil. PloS ONE, 15(8), e0236146. [link](https://doi.org/10.1371/journal.pone.0236146)

**Feitosa, L. M.**, Nunes, J. L. S. (2020). New record of Carcharhinus leucas in an Amazonian River system. Boletim do Laboratório de Hidrobiologia, 30, 62-67. [link](https://doi.org/10.18764/1981-6421e2020.6)

**Feitosa, L. M.**, Dressler, V., Lessa, R. P. T. (2020). Identification of a nursery area for an endangered coastal shark with vertebrae microchemistry: the case study of the smalltail shark *Carcharhinus porosus*. Frontiers in Marine Science, 7, 1-12. [link](https://doi.org/10.3389/fmars.2020.00125)

**Feitosa, L. M.**, Pereira, L. M., Souza-Junior, L. A., Lessa, R. P. T. (2020). Potential distribution and population trends of the smalltail shark *Carcharhinus porosus* inferred from species distribution models and historical catch data. Aquatic Conservation: Marine and Freshwater Ecosystems, 30, 882-891. [link](https://doi.org/10.1002/aqc.3293)

Rodrigues-Filho, L.F.S., **Feitosa, L. M.**, Nunes, J. L., Palmeira, A. R. O., Martins, A. P. B., Giarrizzo, T., Costa, L. F. C., Monteiro, I. L. P., Gemaque, R. Gomes, F., Souza, R. F. C., Sampaio, I. (2020). Molecular identification of ray species traded along the Brazilian Amazon coast. Fisheries Research, 223, 105407. [link](https://doi.org/10.1016/j.fishres.2019.105407)

Wosnick, N., Nunes, A. R. O. P., **Feitosa, L. M.**, Coelho, K. K. F., Brito, R. M. S., Martins, A. P. B., Rincon, G., Nunes, J. L. S. Revisão sobre a diversidade, ameaças e conservação dos elasmobrânquios do Maranhão. In: José Max Barbosa de Oliveira Junior; Lenize Batista Calvão. (Org.). Tópicos Integrados de Zoologia. 1ed. Ponta Grossa: Atena Editora, 2019, p. 44-54. [link](http://dx.doi.org/10.22533/at.ed.1471915105)

Guimarães, E. C., De Brito, P. S., **Feitosa, L. M.**, Carvalho-Costa, L. F., Ottoni, F. P. (2019). A new cryptic species of Hyphessobrycon (Characiformes, Characidae) from the Eastern Amazon, revealed by integrative taxonomy. Zoosystematics and Evolution, 95(2), 345-360. [link](https://doi.org/10.3897/zse.95.34069)

**Feitosa, L. M.**, Martins, A. P. B., Lessa, R. P. T., Barbieri, R., Nunes, J. L. S. (2019). Daggernose shark: an elusive species from Northern South America. Fisheries, 44(3), 144-147. [link](https://doi.org/10.1002/fsh.10205)

**Feitosa, L. M.**, Martins, A. P. B., Giarrizzo, T., Macedo, W., Monteiro, I. L., Gemaque, R., Nunes, J. L. S., Gomes, F., Schneider, H., Sampaio, I., Souza, R., Sales, J. B., Rodrigues-Filho, L. F., Tchaicka, L., Carvalho-Costa, L. F. (2018). DNA-based identification reveals illegal trade of threatened shark species in a global elasmobranch conservation hotspot. Scientific Reports, 8, 3347. [link](https://doi.org/10.1038/s41598-018-21683-5)

Martins, A. P. B., **Feitosa, L. M.**, Lessa, R. P. T., Almeida, Z. S., Heupel, M., Silva, W. M., Tchaicka, L., Nunes, J. L. S. (2018). Analysis of the supply chain and conservation status of sharks (Elasmobranchii: Superorder Selachimorpha) based on fisher knowledge. PLoS ONE, 13, e0193969. [link](https://doi.org/10.1371/journal.pone.0193969)

Guimarães, E. C., De Brito, P. S., **Feitosa, L. M.**, Carvalho-Costa, L. F., Ottoni, F. P. (2018). A new species of Hyphessobrycon Durbin from northeastern Brazil: evidence from morphological data and DNA barcoding (Characiformes, Characidae). ZooKeys, 765, 79-101. [link](https://doi.org/10.3897/zookeys.765.23157)

**Feitosa, L. M.**, Martins, A. P. B., Nunes, J. L. S. 2017. Sawfish (Pristidae) records along the Eastern Amazon coast. Endangered Species Research, 34, 229-234. [link](https://doi.org/10.3354/esr00852)

**Feitosa, L. M.**, Martins, A. P. B., Nunes, J. L. S. 2016. New record of Carcharhinus leucas (Valenciennes, 1839) in an equatorial river system. Marine Biodiversity Records, 9, 87. [link](https://doi.org/10.1186/s41200-016-0094-6)

Martins, A. P. B., Filho, E. S., **Feitosa, L. M.**, Silva, L. P. N., Almeida, Z. S., Nunes, J. L. S. 2015. Sexual dimorphism of sharks from the Amazonian Equatorial Coast. Universitas Scientiarum, 20, 297-304. [link](https://doi.org/10.11144/Javeriana.SC20-3.sdos)

