---
title: "Research"
---

**Shark and ray ecology and conservation**


Sharks and rays (Elasmobranchii) are among the most threatened vertebrates globally. Overfishing is the main extinction threat, mostly caused by bycatch from longline, gillnet, and trawl fisheries. Decreases in their populations could cause substantial disequilibria in the ecosystems they occur because they are meso- and apex-predators occurring in marine and freshwater environments. I am interested in gathering life history and ecological data about data-poor species threatened by fisheries in tropical environments to better inform species status assessments and fisheries management. [Related publications](../pubs/shark_ray/sharks_and_rays.html)

**Fisheries management and policy**


Fishing is one of the last activities in which humans still act as predators. The increase in demand for fish protein and the technological improvements in fishing fleets over the last few decades have placed a strong pressure on fish stocks, with roughly 30% of global fisheries being overfished. While fisheries management is arguably the best approach we have to ensure fish stocks remain sustainable through time, its focus on the target species is not enough to fishing is a sustainable activity. I am interested in evaluating current fisheries management efforts and proposing new alternatives to make management more holistic and effective. [Related publications](../pubs/fish_mgmt/fisheries_mgmt.html)

**Extinction risk from wildlife trade**


Wildlife trade is currently one of the fastest growing forms of exploitation of natural resources globally. The high value paid for some of these products provides a great incentive for harvesters and smugglers to carry out unsustainable harvests. While we often see busts of smuggled shark fins or birds make news headlines, information about where these species are harvested, where are they traded to, and what species are of most interest to traders is scarce. Several other products are completely out of the public's radar, which prevents pressure for further regulation. I am interested in understanding the role wildlife trade practices have in the extinction risk of the exploited species and on how to improve the wildlife trade mechanisms available. [Related publications](../pubs/trade/wildlife_trade.html)
